### ISSUE TITLE
Modularize `bean` and create a `bean init [project_name]` command to generate a desired project structure.

### ISSUE THREAD

**Issue by yu-yk** [retail-ai-inc/bean#4]
In order to do that, we need to do something first
1. Rename `framework` to `bean`. 
2. Move all files, directory structure we wanted into `bean/internal` (I suggest `internal` here because we just use it for code generation not for external use. Go will not export anythings with `internal` package name, which means we can block the bean consumer to import any code from `internal` after they imported `bean` package).
3. Create `bean init [project_name]` command which do the following things:
        a. Create a new folder in current directory named `project_name`.
        b. Copy all the files from `internal` folder into `project_name` folder.

**Comment by yu-yk** [comment]
```
.
├── README
├── bin
├── cmd
│   ├── init.go
│   └── root.go
├── internal
│   ├── boilerplates...
│   ├── boilerplates...
│   └── boilerplates...
├── go.mod
├── go.sum
└── main.go
```

**Comment by tanvir-retailai** [comment]
Project name validation:

```
1. lowercase-letters (a-z0-9) (that may separated by underscores _). Names may not contain spaces or any other special characters.

2. A project name can not start with 0-9 or underscore

3. Cannot use these reserved keywords: break, default, func, interface, select, case, defer, go, map, struct, chan, else, goto, package, switch, const, fallthrough, if, range, type, continue, for, import, return, var.

4. Cannot use these reserved keywords either: append, bool, byte, cap, close, complex, complex64, complex128, uint16, copy, false, float32, float64, imag, int, int8, int16, uint32, int32, int64, iota, len, make, new, nil, panic, uint64, print, println, real, recover, string, true, uint, uint8, uintptr,
```
